name: Deploy to Yandex Cloud Serverless Containers

on:
  push:
    branches: [ work ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/insightica-bot:${{ github.sha }}

      - name: Deploy to Serverless Containers
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: insightica-bot
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-service-account-id: ${{ secrets.YC_VM_SERVICE_ACCOUNT_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/insightica-bot:${{ github.sha }}
          revision-cores: 1
          revision-core-fraction: 100
          revision-memory: 512Mb
          revision-concurrency: 1
          revision-execution-timeout: 600s
          revision-env: |
            TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
            WEBHOOK_HOST=https://bba9mgrrav1hm9jcg23l.containers.yandexcloud.net
            WEBHOOK_PATH=/webhook
            PORT=8443

      - name: Create or Update HTTP Trigger
        run: |
          yc serverless trigger create http \
            --name insightica-webhook-trigger \
            --container-name insightica-bot \
            --folder-id ${{ secrets.YC_FOLDER_ID }} \
            --path /webhook || \
          yc serverless trigger update http \
            --trigger-name insightica-webhook-trigger \
            --path /webhook

      - name: Register Telegram Webhook
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        run: |
          TRIGGER_URL=$(yc serverless trigger get \
            --name insightica-webhook-trigger \
            --folder-id ${{ secrets.YC_FOLDER_ID }} \
            --format json | jq -r '.url')
          curl -s \
            -F "url=${TRIGGER_URL}${{ secrets.WEBHOOK_PATH }}" \
            https://api.telegram.org/bot${TG_BOT_TOKEN}/setWebhook
