name: Deploy to Yandex Cloud Serverless Containers

on:
  push:
    branches: [ work ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем yc CLI
      - name: Setup Yandex Cloud CLI
        uses: nightstory/setup-yc@v1
        with:
          enable-cache: true

      # 3. Логинимся в Container Registry (для docker push)
      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      # 4. Сборка и пуш Docker-образа
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/insightica-bot:${{ github.sha }}

      # 5. Деплой в Serverless Containers
      - name: Deploy to Serverless Containers
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: insightica-bot
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-service-account-id: ${{ secrets.YC_VM_SERVICE_ACCOUNT_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/insightica-bot:${{ github.sha }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-concurrency: 1
          revision-execution-timeout: 600s
          # Передаём в контейнер обе переменные, которые ждёт main.py
          revision-env: |
            TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
            WEBHOOK_HOST=${{ secrets.WEBHOOK_HOST }}
            WEBHOOK_PATH=/webhook

      # 6. Регистрация Telegram-вебхука
      - name: Register Telegram Webhook
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          WEBHOOK_HOST: ${{ secrets.WEBHOOK_HOST }}
          WEBHOOK_PATH: /webhook
        run: |
          WEBHOOK_URL="https://${WEBHOOK_HOST}${WEBHOOK_PATH}"
          echo "Setting Telegram webhook to ${WEBHOOK_URL}"
          curl -s -X POST \
            "https://api.telegram.org/bot${TG_BOT_TOKEN}/setWebhook" \
            -F "url=${WEBHOOK_URL}"
